name: Publish

permissions:
  contents: read

on:
  push:
    tags:
      - 'v[0-9]+.[0-9]+.[0-9]+'

jobs:
  publish:
    name: Publish Images
    runs-on: ubuntu-latest

    permissions:
      contents: write

    steps:
      - name: Checkout
        uses: actions/checkout@v6

      - name: Setup Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Push PDP11
        uses: docker/build-push-action@v6
        with:
          target: pdp11
          push: true
          tags: |
            ${{ secrets.DOCKERHUB_USERNAME }}/pdp11:latest
            ${{ secrets.DOCKERHUB_USERNAME }}/pdp11:${{ github.ref_name }}
          cache-from: type=gha
          cache-to: type=gha,mode=max

      - name: Push Unix v6
        uses: docker/build-push-action@v6
        with:
          target: pdp11-unix-v6
          push: true
          tags: |
            ${{ secrets.DOCKERHUB_USERNAME }}/pdp11-unix-v6:latest
            ${{ secrets.DOCKERHUB_USERNAME }}/pdp11-unix-v6:${{ github.ref_name }}
          cache-from: type=gha
          cache-to: type=gha,mode=max

      - name: Push 2.11BSD
        uses: docker/build-push-action@v6
        with:
          target: pdp11-2.11bsd
          push: true
          tags: |
            ${{ secrets.DOCKERHUB_USERNAME }}/pdp11-2.11bsd:latest
            ${{ secrets.DOCKERHUB_USERNAME }}/pdp11-2.11bsd:${{ github.ref_name }}
          cache-from: type=gha
          cache-to: type=gha,mode=max

      - name: Push 2.11BSD with httpd
        uses: docker/build-push-action@v6
        with:
          target: pdp11-2.11bsd-httpd
          push: true
          tags: |
            ${{ secrets.DOCKERHUB_USERNAME }}/pdp11-2.11bsd-httpd:latest
            ${{ secrets.DOCKERHUB_USERNAME }}/pdp11-2.11bsd-httpd:${{ github.ref_name }}
          cache-from: type=gha
          cache-to: type=gha,mode=max

      - name: Create Release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          version="${{ github.ref_name }}"
          version="${version#v}"
          gh release create "${{ github.ref_name }}" \
            --title "Docker Images ${version}" \
            --draft \
            --generate-notes \
            --verify-tag
